"""multi_company_array_support

Revision ID: d042812ab858
Revises: 8923ea2dcda8
Create Date: 2026-04-27 18:08:02.273294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd042812ab858'
down_revision: Union[str, Sequence[str], None] = '8923ea2dcda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_search_index', sa.Column('company_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_index(op.f('idx_global_search_company'), table_name='global_search_index')
    op.create_index('idx_global_search_company', 'global_search_index', ['company_ids'], unique=False, postgresql_using='gin')
    op.drop_column('global_search_index', 'company_id')
    op.drop_column('global_search_index', 'allowed_branch_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_search_index', sa.Column('allowed_branch_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('global_search_index', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('idx_global_search_company', table_name='global_search_index', postgresql_using='gin')
    op.create_index(op.f('idx_global_search_company'), 'global_search_index', ['company_id'], unique=False)
    op.drop_column('global_search_index', 'company_ids')
    # ### end Alembic commands ###
